In [1]:
import pandas as pd
data={"state":["UP","MP","Maharastra","Rajasthan","Pune","Patna"],
      "year":[2022,2021,2000,2024,2056,2080],
      "pop":[1.4,3.5,2.3,1.3,7.5,8.2]
      }
new_data=pd.DataFrame(data)

In [2]:
new_data

        state  year  pop
0          UP  2022  1.4
1          MP  2021  3.5
2  Maharastra  2000  2.3
3   Rajasthan  2024  1.3
4        Pune  2056  7.5
5       Patna  2080  8.2

In [6]:
new_data.set_index('state',inplace=True)

In [10]:
new_data.loc['MP']

year    2021.0
pop        3.5
Name: MP, dtype: float64

In [11]:
new_data.loc['UP':'Patna']

            year  pop
state
UP          2022  1.4
MP          2021  3.5
Maharastra  2000  2.3
Rajasthan   2024  1.3
Pune        2056  7.5
Patna       2080  8.2

In [12]:
new_data.loc['UP':'Patna':2]

            year  pop
state
UP          2022  1.4
Maharastra  2000  2.3
Pune        2056  7.5

In [13]:
#Fancy indexing
new_data.loc[['MP','Patna']]

       year  pop
state
MP     2021  3.5
Patna  2080  8.2

In [15]:
new_data.iloc[(new_data['MP'].index)]

KeyError: 'MP'

In [24]:
values={"state":["UP","MP","Maharastra","Rajasthan","Pune","Patna"],
      "year":[2022,2021,2000,2024,2056,2080],
      "pop":[1.4,3.5,2.3,1.3,7.5,8.2]
      }
data2=pd.DataFrame(values)

In [56]:
indi=data2.index[data2['state']=='UP']
indi

Index(['A'], dtype='object')

In [59]:
data2.index=['A','B','C','D','E','F']
data2

        state  year  pop
A          UP  2022  1.4
B          MP  2021  3.5
C  Maharastra  2000  2.3
D   Rajasthan  2024  1.3
E        Pune  2056  7.5
F       Patna  2080  8.2

In [47]:
indice=data2.index[data2['pop']>2].tolist() #Finding index based on condition

In [60]:
data2

        state  year  pop
A          UP  2022  1.4
B          MP  2021  3.5
C  Maharastra  2000  2.3
D   Rajasthan  2024  1.3
E        Pune  2056  7.5
F       Patna  2080  8.2

In [64]:
data2.loc['A':'D']

        state  year  pop
A          UP  2022  1.4
B          MP  2021  3.5
C  Maharastra  2000  2.3
D   Rajasthan  2024  1.3