# **Session 7: Linear Regression & Gradient Descent**
**California Housing Dataset**

## **Learning Objectives**
- Understand Gradient Descent theory
- Implement Gradient Descent using custom class
- Evaluate regression models
- Compare with scikit-learn

In [4]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.datasets import fetch_california_housing
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import StandardScaler, PolynomialFeatures
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

In [5]:
# Load Data

housing = fetch_california_housing()
df = pd.DataFrame(housing.data, columns=housing.feature_names)
df['MedHouseVal'] = housing.target

print("Dataset Shape:", df.shape)
df.head()

Dataset Shape: (20640, 9)

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude,MedHouseVal
0,8.3252,41.0,6.984127,1.023810,322.0,2.555556,37.88,-122.23,4.526
1,8.3014,21.0,6.238137,0.971880,2401.0,2.109842,37.86,-122.22,3.585
2,7.2574,52.0,8.288136,1.073446,496.0,2.802260,37.85,-122.24,3.521
3,5.6431,52.0,5.817352,1.073059,558.0,2.547945,37.85,-122.25,3.413
4,3.8462,52.0,6.281853,1.081081,565.0,2.181467,37.85,-122.25,3.422

## **Theory: Gradient Descent**

**Cost Function (MSE):**  
$$ J = \frac{1}{2m} \sum (\hat{y} - y)^2 $$

**Update Rules:**  
$$ b := b - \alpha \cdot \frac{\partial J}{\partial b} $$
$$ m := m - \alpha \cdot \frac{\partial J}{\partial m} $$

## **Gradient Descent Class**

In [6]:
class GDRegressor:

    def __init__(self,learning_rate=0.01,epochs=1000):
      self.learning_rate=learning_rate
      self.epochs=epochs
      self.m=0

      self.b=0


      def fit(self, X, y):
        X=X.flatten()
        n=len(X)


        for _ in range(self.epochs):
          y_pred=self.m*X+self.b# Step 1: Predict
            
           # Step 2: Calculate Gradients
          dm=(-2/n)*np.sum((y-y_pred)*X)
          db=(-2/n)*np.sum(y-y_pred)
           # Step 3: Update Parameters
          self.n=self.n-self.learning_rate*dm
          self.b=self.b-self.leaning_rate*db

      print("Training Completed")
      print(f"Slope (m)     : {self.m:.4f}")
      print(f"Intercept (b) : {self.b:.4f}")

      def predict(self, X):
         X=X.flatten()
         return self.n*X+self.b

## **Train Model (Single Feature: MedInc)**

In [7]:
# Prepare data
X=df[['MedInc']].values
y=df[['MedHouseVal']].values

In [8]:
# Scale feature
df

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude,MedHouseVal
0,8.3252,41.0,6.984127,1.023810,322.0,2.555556,37.88,-122.23,4.526
1,8.3014,21.0,6.238137,0.971880,2401.0,2.109842,37.86,-122.22,3.585
2,7.2574,52.0,8.288136,1.073446,496.0,2.802260,37.85,-122.24,3.521
3,5.6431,52.0,5.817352,1.073059,558.0,2.547945,37.85,-122.25,3.413
4,3.8462,52.0,6.281853,1.081081,565.0,2.181467,37.85,-122.25,3.422
...,...,...,...,...,...,...,...,...,...
20635,1.5603,25.0,5.045455,1.133333,845.0,2.560606,39.48,-121.09,0.781
20636,2.5568,18.0,6.114035,1.315789,356.0,3.122807,39.49,-121.21,0.771
20637,1.7000,17.0,5.205543,1.120092,1007.0,2.325635,39.43,-121.22,0.923
20638,1.8672,18.0,5.329513,1.171920,741.0,2.123209,39.43,-121.32,0.847
20639,2.3886,16.0,5.254717,1.162264,1387.0,2.616981,39.37,-121.24,0.894

In [11]:
# Train using our GD Class
gd=GDRegressor(learning_rate=0.01,epochs=500)
gd.fit()

Training Completed
Slope (m)     : 0.0000
Intercept (b) : 0.0000

AttributeError: 'GDRegressor' object has no attribute 'fit'

## **Compare with scikit-learn**

In [12]:
lr=LinearRegression()
lr.fit(X_scaled,y)

NameError: name 'X_scaled' is not defined

In [10]:
print("scikit-learn Slope:", lr.coef_[0])
print("scikit-learn Intercept:", lr.intercept_)

NameError: name 'lr' is not defined

## **Model Evaluation**

In [ ]:
X_train,X_test,y_train,y_test=train_test_split(X_scaled,y_test)

## **Linear vs Polynomial Regression**

In [ ]:
# Train Linear Regression

In [ ]:
# Train Polynomial Regression

In [ ]:
# Create X values from minimum to maximum
X_line = np.linspace(X.min(), X.max(), 100).reshape(-1, 1)

In [ ]:
# Predictions

In [ ]:
# Plot
plt.figure(figsize=(10,6))

plt.scatter(X, y, color="blue", alpha=0.4, label="Actual Data")
plt.plot(X_line, y_linear, color="red", label="Linear Regression")
plt.plot(X_line, y_poly, color="green", label="Polynomial Regression")

plt.xlabel("MedInc")
plt.ylabel("MedHouseVal")
plt.title("Linear vs Polynomial Regression")
plt.legend()
plt.show()

## **Most Important Feature**

In [ ]:


pd.DataFrame({
    'Feature': housing.feature_names,
    'Std_Coefficient': std_model.coef_
}).sort_values(by='Std_Coefficient', key=abs, ascending=False)

# Adjusted R² Score

R² Score measures how much of the variance in the target variable is explained by the model.

However, R² has one limitation:

- Adding more features to a model will **never decrease** the R² score, even if those features are irrelevant.

Adjusted R² solves this problem by penalizing the model for adding unnecessary features.

### Formula

Adjusted R² = 1 - ((1 - R²) × (n - 1)) / (n - p - 1)

Where:
- R² = Coefficient of Determination
- n = Number of observations (samples)
- p = Number of independent variables (features)

A higher Adjusted R² indicates that the added features genuinely improve the model.

In [ ]:
# Predict the target values
y_pred = std_model.predict(X_scaled_all)

# Calculate R² Score
# Number of samples
# Number of features
# Calculate Adjusted R²
print(f"R² Score         : {r2:.4f}")
print(f"Adjusted R² Score: {adjusted_r2:.4f}")