In [1]:
import pandas as pd

In [2]:
bat=pd.read_csv('batsman_runs_ipl.csv')
bat.sample(5)

               batter  batsman_run
479       SA Asnodkar          423
155  DPMD Jayawardene         1808
482         SB Jakati           28
67      Anirudh Singh           63
180         GH Vihari          284

### Rank method is only applicable on series not in panda

In [9]:
bat['batting_rank']=bat['batsman_run'].rank(ascending=False)
bat.sort_values('batting_rank',inplace=True)
bat

          batter  batsman_run  batting_rank
569      V Kohli         6634           1.0
462     S Dhawan         6244           2.0
130    DA Warner         5883           3.0
430    RG Sharma         5881           4.0
493     SK Raina         5536           5.0
..           ...          ...           ...
467      S Ladda            0         594.0
512  SS Cottrell            0         594.0
102      C Nanda            0         594.0
65    Akash Deep            0         594.0
249      K Yadav            0         594.0

[605 rows x 3 columns]

In [ ]:
bat.set_index('batter',inplace=True)#set_index only work on dataframe

In [ ]:
#reset_index(series+dataframe)
#way to replace existing index without losing

bat.reset_index().set_index('batting_rank')

                   batter  batsman_run
batting_rank
1.0               V Kohli         6634
2.0              S Dhawan         6244
3.0             DA Warner         5883
4.0             RG Sharma         5881
5.0              SK Raina         5536
...                   ...          ...
594.0             S Ladda            0
594.0         SS Cottrell            0
594.0             C Nanda            0
594.0          Akash Deep            0
594.0             K Yadav            0

[605 rows x 2 columns]

### When you want to convert series into dataframe use reset_index into the series