In [1]:
import pandas as pd

In [2]:
ipl=pd.read_csv('ipl-matches.csv')

In [ ]:
ipl[ipl['MatchNumber']=='Final'][['Season','WinningTeam']] #Finding Winning team of every season in final matches

      Season            WinningTeam
0       2022         Gujarat Titans
74      2021    Chennai Super Kings
134  2020/21         Mumbai Indians
194     2019         Mumbai Indians
254     2018    Chennai Super Kings
314     2017         Mumbai Indians
373     2016    Sunrisers Hyderabad
433     2015         Mumbai Indians
492     2014  Kolkata Knight Riders
552     2013         Mumbai Indians
628     2012  Kolkata Knight Riders
702     2011    Chennai Super Kings
775  2009/10    Chennai Super Kings
835     2009        Deccan Chargers
892  2007/08       Rajasthan Royals

In [21]:
#Finding Winning team of every season in final matches
mask=ipl['MatchNumber']=='Final'
new_data=ipl[mask]
new_data[['Season','WinningTeam']]

      Season            WinningTeam
0       2022         Gujarat Titans
74      2021    Chennai Super Kings
134  2020/21         Mumbai Indians
194     2019         Mumbai Indians
254     2018    Chennai Super Kings
314     2017         Mumbai Indians
373     2016    Sunrisers Hyderabad
433     2015         Mumbai Indians
492     2014  Kolkata Knight Riders
552     2013         Mumbai Indians
628     2012  Kolkata Knight Riders
702     2011    Chennai Super Kings
775  2009/10    Chennai Super Kings
835     2009        Deccan Chargers
892  2007/08       Rajasthan Royals

In [28]:
ipl['SuperOver'].value_counts()['Y']

np.int64(14)

In [32]:
(ipl['SuperOver']=='Y').sum()

np.int64(14)

In [33]:
ipl[ipl['SuperOver']=='Y'].shape[0]

14

In [41]:
#How many matches won by CSK on kolkata
ipl[(ipl['City']=='Kolkata') & (ipl['WinningTeam']=='Chennai Super Kings')].shape[0]

5

In [47]:
#Toss Winner is Match Winner percentage
toss_winner=ipl[ipl['TossWinner']==ipl['WinningTeam']].shape[0]
(toss_winner/len(ipl))*100

51.473684210526315