In [1]:
import pandas as pd

In [2]:
df=pd.DataFrame({'cse':[120], 'ece':[100], 'mech':[50]})

In [5]:
df

   cse  ece  mech
0  120  100    50

In [7]:
df.melt(var_name='Branch',value_name='Number of students')

  Branch  Number of students
0    cse                 120
1    ece                 100
2   mech                  50

In [13]:
df2=pd.DataFrame({
    'branch':['cse','ece','mech'],
    '2020':[100,150,60],
    '2021':[23,435,654],
    '2022':[12,23,43]
})
df2

  branch  2020  2021  2022
0    cse   100    23    12
1    ece   150   435    23
2   mech    60   654    43

In [19]:
df2.melt(id_vars=['branch'],var_name='Year',value_name="Number of student")#branh wll not convert as row

  branch  Year  Number of student
0    cse  2020                100
1    ece  2020                150
2   mech  2020                 60
3    cse  2021                 23
4    ece  2021                435
5   mech  2021                654
6    cse  2022                 12
7    ece  2022                 23
8   mech  2022                 43