In [1]:
import pandas as pd

In [16]:
index_val = [
    ('cse',2019), ('cse',2020), ('cse',2021), ('cse',2022),
    ('ece',2019), ('ece',2020), ('ece',2021), ('ece',2022)
]

index = pd.MultiIndex.from_tuples(index_val)

df = pd.DataFrame(
    [[1,2],[3,4],[5,6],[7,8],
     [9,10],[11,12],[13,14],[15,16]],
    index=index,
    columns=['avg_package','students']
)#8x2 size

In [19]:
df.shape

(8, 2)

In [26]:
df['avg_package']

cse  2019     1
     2020     3
     2021     5
     2022     7
ece  2019     9
     2020    11
     2021    13
     2022    15
Name: avg_package, dtype: int64

In [ ]:
df2=pd.DataFrame(
    [
        [1,2,0,0],
        [3,4,0,0],
        [5,6,0,0],
        [7,8,0,0],
    ],
    index=[2019,2020,2021,2022],
    columns=pd.MultiIndex.from_product([['delhi','mumbai'],['avg_package','students']])#this is happenign because in pandas rows and columns are same
    
)

In [33]:
df2['delhi']['avg_package']

2019    1
2020    3
2021    5
2022    7
Name: avg_package, dtype: int64

In [34]:
df2.loc[2019]

delhi   avg_package    1
        students       2
mumbai  avg_package    0
        students       0
Name: 2019, dtype: int64

In [38]:
#4 dimensional
df3=pd.DataFrame(
    [
        [1,2,0,0],
        [3,4,0,0],
        [5,6,0,0],
        [7,8,0,0],
        [9,10,0,0],
        [9,10,0,0],
        [9,10,0,0],
        [9,10,0,0]
    ],
    index=index,
    columns=pd.MultiIndex.from_product([['delhi','mumbai'],['avg_package','students']])#this is happenign because in pandas rows and columns are same
    
)

In [40]:
df3.shape

(8, 4)

In [50]:
dff=df.unstack().unstack()
dff[3]

C:\Users\mohds\AppData\Local\Temp\ipykernel_23768\2605143516.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  dff[3]

np.int64(11)

In [51]:
type(df.unstack().unstack())#series> because there is no columns

pandas.core.series.Series

In [55]:
dfff=df.unstack().stack().stack()

C:\Users\mohds\AppData\Local\Temp\ipykernel_23768\2966593002.py:1: FutureWarning: The previous implementation of stack is deprecated and will be removed in a future version of pandas. See the What's New notes for pandas 2.1.0 for details. Specify future_stack=True to adopt the new implementation and silence this warning.
  dfff=df.unstack().stack().stack()

In [58]:
type(dfff)

pandas.core.series.Series

In [60]:
dfff

cse  2019  avg_package     1
           students        2
     2020  avg_package     3
           students        4
     2021  avg_package     5
           students        6
     2022  avg_package     7
           students        8
ece  2019  avg_package     9
           students       10
     2020  avg_package    11
           students       12
     2021  avg_package    13
           students       14
     2022  avg_package    15
           students       16
dtype: int64

In [59]:
dfff.unstack()

          avg_package  students
cse 2019            1         2
    2020            3         4
    2021            5         6
    2022            7         8
ece 2019            9        10
    2020           11        12
    2021           13        14
    2022           15        16

In [62]:
df3.loc[('cse',2019):('ece',2022):2]

               delhi               mumbai
         avg_package students avg_package students
cse 2019           1        2           0        0
    2021           5        6           0        0
ece 2019           9       10           0        0
    2021           9       10           0        0

In [64]:
df3.iloc[0:5:2]

               delhi               mumbai
         avg_package students avg_package students
cse 2019           1        2           0        0
    2021           5        6           0        0
ece 2019           9       10           0        0

In [81]:
df3['delhi'][['avg_package','students']]

          avg_package  students
cse 2019            1         2
    2020            3         4
    2021            5         6
    2022            7         8
ece 2019            9        10
    2020            9        10
    2021            9        10
    2022            9        10

In [72]:
df3.iloc[:,1:3]

            delhi      mumbai
         students avg_package
cse 2019        2           0
    2020        4           0
    2021        6           0
    2022        8           0
ece 2019       10           0
    2020       10           0
    2021       10           0
    2022       10           0

In [73]:
df3.iloc[[0,4],[1,2]]

            delhi      mumbai
         students avg_package
cse 2019        2           0
ece 2019       10           0

In [83]:
df3.sort_index(ascending=False)#2 level pe sorting

               delhi               mumbai
         avg_package students avg_package students
ece 2022           9       10           0        0
    2021           9       10           0        0
    2020           9       10           0        0
    2019           9       10           0        0
cse 2022           7        8           0        0
    2021           5        6           0        0
    2020           3        4           0        0
    2019           1        2           0        0

In [85]:
df3.sort_index(ascending=[False,True])#1 level pe descending and 2 p ascending

               delhi               mumbai
         avg_package students avg_package students
ece 2019           9       10           0        0
    2020           9       10           0        0
    2021           9       10           0        0
    2022           9       10           0        0
cse 2019           1        2           0        0
    2020           3        4           0        0
    2021           5        6           0        0
    2022           7        8           0        0

In [87]:
df3.sort_index(level=1,ascending=False)#year(level1) based sorting

               delhi               mumbai
         avg_package students avg_package students
ece 2022           9       10           0        0
cse 2022           7        8           0        0
ece 2021           9       10           0        0
cse 2021           5        6           0        0
ece 2020           9       10           0        0
cse 2020           3        4           0        0
ece 2019           9       10           0        0
cse 2019           1        2           0        0

In [88]:
df3.transpose()

                    cse                 ece
                   2019 2020 2021 2022 2019 2020 2021 2022
delhi  avg_package    1    3    5    7    9    9    9    9
       students       2    4    6    8   10   10   10   10
mumbai avg_package    0    0    0    0    0    0    0    0
       students       0    0    0    0    0    0    0    0

In [ ]:
#swaplevel
df3.swaplevel()#swap index level1 to level2

               delhi               mumbai
         avg_package students avg_package students
2019 cse           1        2           0        0
2020 cse           3        4           0        0
2021 cse           5        6           0        0
2022 cse           7        8           0        0
2019 ece           9       10           0        0
2020 ece           9       10           0        0
2021 ece           9       10           0        0
2022 ece           9       10           0        0

In [91]:
df3.swaplevel(axis=1)#swap column

         avg_package students avg_package students
               delhi    delhi      mumbai   mumbai
cse 2019           1        2           0        0
    2020           3        4           0        0
    2021           5        6           0        0
    2022           7        8           0        0
ece 2019           9       10           0        0
    2020           9       10           0        0
    2021           9       10           0        0
    2022           9       10           0        0