##Load Dataset

xmin-max=(x-xmin)/(xmax-xmin)
Robust scalar=Xr=(X-Xmedian)/IQR

# Outlier Detection and Treatment on Titanic Dataset
This notebook covers all questions from the exercise.

In [11]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from scipy.stats import zscore

df=pd.read_csv('train.csv')
df=df[['Age','Fare']].dropna()
df.head()

    Age     Fare
0  22.0   7.2500
1  38.0  71.2833
2  26.0   7.9250
3  35.0  53.1000
4  35.0   8.0500

In [ ]:
#check missing value
df['fare']

np.int64(0)

In [ ]:
#shape
df.shape

(714, 2)

In [ ]:
#info
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 714 entries, 0 to 890
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Age     714 non-null    float64
 1   Fare    714 non-null    float64
dtypes: float64(2)
memory usage: 16.7 KB

In [13]:
#describe
df['Fare'].describe()

count    714.000000
mean      34.694514
std       52.918930
min        0.000000
25%        8.050000
50%       15.741700
75%       33.375000
max      512.329200
Name: Fare, dtype: float64

In [ ]:
# Visualization for fare and age
# Histogram
# KDE plot
# Boxplot
# skew

In [14]:
#skew
df['Fare'].skew()

np.float64(4.6536303678277395)

In [15]:
df['Age'].skew()

np.float64(0.38910778230082693)

In [22]:
q3=df['Fare'].quantile(0.75)
q1=df['Fare'].quantile(0.25)
IQR=q3-q1
upper_bound=q3+1.5*(IQR)
Lower_bound=q1-1.5*(IQR)
print('Upper_Limit',upper_bound)
print("Lower_bound ",Lower_bound)

Upper_Limit 71.3625
Lower_bound  -29.937499999999996

In [24]:
#outliers

df[df['Fare']>upper_bound]

      Age      Fare
27   19.0  263.0000
34   28.0   82.1708
52   49.0   76.7292
61   38.0   80.0000
62   45.0   83.4750
..    ...       ...
820  52.0   93.5000
829  62.0   80.0000
835  39.0   83.1583
856  45.0  164.8667
879  56.0   83.1583

[94 rows x 2 columns]

In [ ]:
#Fixing Outliers 
#1. Trimming - Disadvantages=Dataloss
new_df=df[(df['Fare']<upper_bound) & (df['Fare']>Lower_bound)]
new_df

      Age     Fare
0    22.0   7.2500
1    38.0  71.2833
2    26.0   7.9250
3    35.0  53.1000
4    35.0   8.0500
..    ...      ...
885  39.0  29.1250
886  27.0  13.0000
887  19.0  30.0000
889  26.0  30.0000
890  32.0   7.7500

[620 rows x 2 columns]

## Method : Detecting Outliers Using IQR (Interquartile Range)

**What is IQR (Interquartile Range)?** The Interquartile Range (IQR) is a statistical measure that represents the spread of the middle 50% of the data. It measures the distance between the first quartile (Q1) and the third quartile (Q3).

In simple words, IQR tells us how spread out the central half of the dataset is, while ignoring extreme values (outliers). Because it focuses only on the middle 50% of the data, IQR is less affected by outliers than measures like the range or standard deviation.

Formula: `IQR = Q3 − Q1`

Where,
- Q1 = 25th Percentile
- Q3 = 75th Percentile

An observation is considered an *outlier* if `Value < Q1 − 1.5 × IQR` or `Value > Q3 + 1.5 × IQR`.

<img src="attachment:9046fea3-3b43-4977-9f53-f8fde0fc15fe.png" width="50%">

In [ ]:
# find q1

In [ ]:
# find q2

np.float64(8.05)

In [ ]:
#calculate IQR and show the value

np.float64(33.375)

In [ ]:
# find lower bound and upper bound

Finding Outliers

      age        fare    fare_z  fare_zscore
27   19.0  193.451303  4.317274     4.314250
34   28.0   82.170800  0.897780     0.897151
52   49.0   76.729200  0.794879     0.794322
61   38.0   80.000000  0.856730     0.856130
62   45.0   83.475000  0.922443     0.921797
..    ...         ...       ...          ...
820  52.0   93.500000  1.112016     1.111237
829  62.0   80.000000  0.856730     0.856130
835  39.0   83.158300  0.916454     0.915812
856  45.0  164.866700  2.461566     2.459842
879  56.0   83.158300  0.916454     0.915812

[94 rows x 4 columns]

Empty DataFrame
Columns: [age, fare, fare_z, fare_zscore]
Index: []

In [ ]:
# Percentage of Outliers

###Trimming

In [ ]:
# Trimming

      age     fare    fare_z  fare_zscore
0    22.0   7.2500 -0.518978    -0.518614
1    38.0  71.2833  0.691897     0.691412
2    26.0   7.9250 -0.506214    -0.505859
3    35.0  53.1000  0.348049     0.347805
4    35.0   8.0500 -0.503850    -0.503497
..    ...      ...       ...          ...
885  39.0  29.1250 -0.105320    -0.105246
886  27.0  13.0000 -0.410245    -0.409958
887  19.0  30.0000 -0.088774    -0.088711
889  26.0  30.0000 -0.088774    -0.088711
890  32.0   7.7500 -0.509523    -0.509166

[620 rows x 4 columns]

In [ ]:
new_df.shape

(620, 4)

##Graph plot

In [ ]:
#compare

(714, 2)

###Capping-> IQR

In [ ]:
 
new_df_cap=df.copy()
new_df_cap['Fare']=np.where(new_df_cap['Fare']>upper_bound,
                            upper_bound,
                            np.where(new_df_cap['Fare']<Lower_bound,Lower_bound,
                                     new_df_cap['Fare']))
new_df_cap.shape

(714, 2)

In [ ]:
#compare

In [35]:
new_df_cap.describe()

              Age        Fare
count  714.000000  714.000000
mean    29.699118   26.135708
std     14.526497   22.318928
min      0.420000    0.000000
25%     20.125000    8.050000
50%     28.000000   15.741700
75%     38.000000   33.375000
max     80.000000   71.362500

## Method : Detecting Outliers Using Z-Score

**What is Z-Score?** A Z-score (also called the *Standard Score*) is a statistical measure that indicates how many standard deviations a data point is away from the mean (average) of a dataset.

In simple words, It tells us how far a value is from the average (or mean) value of the dataset.

$$z = \frac{x - \mu}{\sigma}$$

Where,
- x = Data value
- μ (mu) = Mean of the dataset
- σ (sigma) = Standard deviation

Observation:
- A positive Z-score means the value is above the mean.
- A negative Z-score means the value is below the mean.
- A Z-score of 0 means the value is exactly equal to the mean.

Generally,
- $Z > 3$ → Outlier
- $Z < -3$ → Outlier

<img src="attachment:fcb5d7aa-0d47-43ec-bc2b-43ae957504bb.png" width="50%">
<img src="attachment:83f94b6c-3458-4952-87a5-2af77e3e7bce.png" width="50%">

##Calculate Z-score

In [37]:
df['fare_score']=(df['Fare']-df['Fare'].mean())/df['Fare'].std()
df

      Age     Fare  fare_score
0    22.0   7.2500   -0.518614
1    38.0  71.2833    0.691412
2    26.0   7.9250   -0.505859
3    35.0  53.1000    0.347805
4    35.0   8.0500   -0.503497
..    ...      ...         ...
885  39.0  29.1250   -0.105246
886  27.0  13.0000   -0.409958
887  19.0  30.0000   -0.088711
889  26.0  30.0000   -0.088711
890  32.0   7.7500   -0.509166

[714 rows x 3 columns]

##Find Outliers

In [40]:
# Write your code here
outliers_zscore=df[(df['fare_score']>3) | (df['fare_score']<-3)]
len(outliers_zscore)

18

##Count Outliers

In [ ]:
# Write your code here

##Percentage

In [ ]:
# Write your code here

##Find Boundary

Lower = Mean − 3σ

Upper = Mean + 3σ

In [42]:
# Write your code here approach first
print("upper limitd ",df['Fare'].mean()+3*df['Fare'].std())
print("Lower limitd ",df['Fare'].mean()-3*df['Fare'].std())

upper limitd  193.45130251323292
Lower limitd  -124.06227450202844

###Trimming-> Zscore

In [44]:
#trimming
# second with the help of |Z| = 3
new_df=df[(df['fare_score']>3) & (df['fare_score']<-3)]
new_df

Empty DataFrame
Columns: [Age, Fare, fare_score]
Index: []

In [45]:
new_df.shape

(0, 3)

In [ ]:
#compare

###Capping-> Zscore

In [ ]:
#applying

In [ ]:
df_Zcap  = df.copy()

In [ ]:
#compare

In [ ]:
df_Zcap.shape

(714, 4)

## 4. Real-World Applications

Outlier detection is widely used in:
1. Fraud Detection
2. Banking and Finance
3. Healthcare
4. Insurance Claims
5. Manufacturing Quality Control
6. Sales Analysis
7. Customer Behavior Analysis
8. Sensor Data Monitoring